### ISSUE TITLE
mongodb link

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/foodolog#4]
https://dashboard.heroku.com/apps/loopback-ian-sandbox

use this link instead of connecting local mongo install
`mongodb://heroku_t0vwqxrx:c6lhpnqg9fm6qnquf05b1im8c0@ds163418.mlab.com:63418/heroku_t0vwqxrx`

You'll need to have a loopback-connector-mongo package in order to setup it well.

Sample: https://github.com/GroceriStar/groceristar/blob/master/server/datasources.json

**Comment by iankiku** [comment]
Ok

**Comment by atherdon** [comment]
it's for later :) i creating a lot of not finished tasks, so tasks that
was not assigned to you - they mine :)
just wanted to move it from my head into task tracker


On 10-Mar-2018 at 12:59 AM, Ian Kiku wrote:


Ok

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/foodolog/issues/4#issuecomment-371987574>,
or mute the thread

**Comment by atherdon** [comment]
updated the info
