### ISSUE TITLE
raven/sentry configuration

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/foodolog#6]
Install raven package

`Raven.config('https://77aa2ee9a7ce484497f56278982a0809@sentry.io/305339').install()`

Init:
https://github.com/GroceriStar/groceristar/blob/master/server/server.js#L17

How to use this tracer:
https://github.com/GroceriStar/groceristar/blob/master/server/server.js#L60

if you'll cover your code well with this tracer - when you'll break something - I'll receive an email notification and will be able to understand more clearly what was goes wrong.

![image](https://user-images.githubusercontent.com/1469198/37542679-b443d8f0-2967-11e8-8d98-7fc3e9aabe6b.png)

**Comment by iankiku** [comment]
ok great

**Comment by atherdon** [comment]
Tell me when it'll be done

**Comment by iankiku** [comment]
I think I've difficulty setting this up but not very sure how it should work in this case, also looking at the example code and the one you provided. 


try {
//try config
  
  }

  // console.log(config);
} catch (err) {
  console.trace(err);
  Raven.captureException(err);
  process.exit(1); // fatal
};

Thats what i included in the sever.js

**Comment by atherdon** [comment]
it's how it works on this loopback version. 
you did well. I'm closing this issue

**Comment by iankiku** [comment]
Ok, that's a relief, there's is a lot going here as far as learning.
thanks

**Comment by atherdon** [comment]
to be honest, Loopback give a great tool for setting up things like raven,
you can see that approach at middleware.json
but i didn't figure out how to use it :) tried few times - not worked well
for me.


On 22-Mar-2018 at 01:06 AM, Ian Kiku wrote:


Ok, that's a relief, there's is a lot going here as far as learning.
thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/foodolog/issues/6#issuecomment-375144986>,
or mute the thread
